spring.application.name=eureka-server
server.port=${SERVER_PORT:8761}

# Standalone Eureka server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}

management.endpoints.web.exposure.include=health,info

