spring.application.name=notification-service

# SERVER
server.port=${SERVER_PORT:5000}

# KAFKA
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:29092}

spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:notification-group}
spring.kafka.consumer.auto-offset-reset=earliest

# Key & Value deserializer
# deserialize JSON
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# serialize JSON
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# MAIL (SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# EUREKA
eureka.client.enabled=${EUREKA_ENABLED:true}
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eureka-server:8761/eureka}

# ACTUATOR
management.endpoints.web.exposure.include=health
